### PR TITLE
Fixed attributes should contain all NOT NULL columns/relations

### PR DESCRIPTION
**Pull request by Ladas**
Currently we were just adding columns with presence validation
so we need to extend that to include NOT NULL constraints defined
in the DB.

### CODE REVIEW

**Comment by Ladas** [comment]
@agrare I'd need this released for the Tower workflow structure (there is saving of cycle that was failing because of this)

**Comment by lpichler** [comment]
@agrare can we create release with this PR ?


When I was collecting new join table(`service_instance_service_credential`) between `service_instances` and `service_offerings`  
I got this error:
https://pastebin.com/p6yu2AVy
 
Issue is that source_id is missing in `AS updated_values (` statement.
Screenshot 2020-02-06 at 16 13 36

Using version 0.3.1 did not help but with this PR it is working.


thanks!

**Comment by agrare** [comment]
:+1: yes I'll release one now

**Comment by agrare** [comment]
Released https://rubygems.org/gems/inventory_refresh/versions/0.3.2

**Comment by lpichler** [comment]
🚀 🏎  thanks @agrare it was super fast 🏎 🚀

**Pull request merged**
